export const HERO_CONTENT = `Aspiring Software Engineer dedicated to making a meaningful impact in the tech industry.`
export const ABOUT_TEXT = `I'm a senior majoring in Computer Science at the University of Wisconsin-Madison, graduating in Spring 2025. Skilled in backend, frontend and full-stack development, and experienced in optimizing APIs and building scalable applications. Passionate about leveraging technology to solve real-world problems using data, AI, and cloud platforms.`;

export const EXPERIENCES = [
  {
    year: "September 2024 - Present",
    role: "Website Director",
    company: "The Vault UW-Madison",
    description: [
      `Led the development and maintenance of the official website for The Vault, ensuring a seamless user experience and up-to-date content, resulting in a 25% increase in user engagement.`,
      `Oversaw website performance, troubleshooting technical issues, and implementing best practices for SEO and accessibility, which improved search engine rankings by 15% and reduced bounce rates by 10%.`,
      `Analyze website traffic and user engagement using analytics tools to optimize user flow and improve overall performance.\n`
    ],
    technologies: [],
  },
  {
    year: "June, 2024 - August, 2024",
    role: "Full-Stack Software Engineering Intern",
    company: "Handshake",
    description: [
      `Developed a Tone Slider feature for GenAI on the Handshake site using Python, React, and TypeScript, enabling real-time enhancement of profile summaries and improving user personalization. The feature is live to 100% of users.`,
      `Achieved a 70%+ increase in usage of the Tone Slider feature, with a 50% increase in students saving their summaries generated by the Tone Slider. The success of this feature prompted plans for release in Europe.`,
      `Optimized LLM/GenAI response times by implementing prompt tuning and retrieval-augmented generation (RAG), reducing latency and improving user experience.`,
      `Refactored and version-controlled API endpoints using GoLang, Ruby, and GraphQL to enhance efficiency, scalability, and maintainability, contributing to a more robust backend infrastructure.`,
      `Managed the product lifecycle from conception to launch, including user feedback integration and iterative improvements for continuous product enhancement.`
      ],
    technologies: ["Python", "React", "TypeScript", "GoLang", "Ruby", "Segments"],
  },
  {
    year: "May, 2023 - July, 2023",
    role: "Software Engineering Intern",
    company: "Sant Nirankari Charitable Foundation",
    description: [
      `Revamped the foundation's website using React.js, Node.js, HTML, and CSS, achieving >95% reliability and enhanced user experience.`,
      `Conducted 10+ workshops to teach Java to underrepresented groups, fostering diversity in tech.`,
      `Implemented troubleshooting techniques to resolve website issues, improving operational efficiency.`
    ],
    technologies: ["React.js", "Node.js", "HTML", "CSS"],
  },
  {
    year: "January, 2022 - May, 2023",
    role: "Teaching Assistant",
    company: "Arizona State University",
    description: [
      `Collaborated with professors for CSE110 Principles of Programming while mentoring 18+ students for Data Structures and Algorithms in Java.`,
      `Instructed ~300 students on linear programming and statistics.`
    ],
    technologies: ["Java", "Data Structures", "Algorithms", "Statistics"],
  },
  {
    year: "November, 2021 - May, 2023",
    role: "Teaching Assistant",
    company: "Arizona State University",
    description: [
      `Optimized database management for 20+ college sports teams through SQL, enhancing data accuracy and consistency while reducing manual data correction efforts by 50%.`,
      `Managed configuration management tasks to ensure data integrity across platforms.`,
      `Delivered 3 scalable data pipelines to assist event coordinators with fetching data and storing customer records in Microsoft Office and Google Workspace.`
    ],
    technologies: ["SQL", "Microsoft Office", "Google Workspace"],
  },

];

export const PROJECTS = [
  {
    title: "Sonic Study",
    type: "Android Application",
    description: [
      `Revolutionized an accessibility-focused flashcard application using Kotlin, Room Database, and Microsoft Azure to support users with visual impairments or dyslexia, providing an innovative audio-based study solution.`,
      `Executed core features such as voice-based input and question-answer pairing using Web Speech API, enhancing the user experience through seamless audio interactions.`,
      `Led user testing and feedback sessions, resulting in a 20% increase in user satisfaction with app usability and audio clarity.`
    ],
    technologies: [`Kotlin`, `Room Database`, `Microsoft Azure`, `Web Speech API`]
  },
  {
    title: "Post-Stroke Recovery Application",
    type: "Web Development",
    description: [
      `Developed a web application using HTML, CSS, and JavaScript that employs gamification to aid in the rehabilitation of stroke victims.`,
      `Improved UI/UX based on user feedback from 30+ participants, increasing user satisfaction and engagement.`
    ],
    technologies: ["HTML", "CSS", "JavaScript"],
  },
  {
    title: "Book Review Web Application",
    type: "Full Stack Web Development",
    description: [
      `Designed a full-stack web application with Node.js, React.js, and PostgreSQL to manage and display personal book reviews.`,
      `Built interactive features, including filtering and sorting, to enhance data accessibility and user interaction.`
    ],
    technologies: ["Node.js", "React.js", "PostgreSQL"],
  },
  {
    title: "Flight Router",
    type: "Algorithm Design and Implementation",
    description: [
      `Revolutionized a Java application that analyzes airport data to compute the shortest routes and flight connections, enhancing travel planning efficiency.`,
      `Implemented complex algorithms to handle dynamic user inputs and provide real-time results.`
    ],
    technologies: ["Java", "Algorithms"],
  },
  {
    title: "Movie Timer",
    type: "Java Application Development",
    description: [
      `Implemented a movie timer app with a Java backend, utilizing a Red-Black Tree to manage and access movie data efficiently.`,
      `Enhanced search functionality to identify shortest movies within specified duration ranges, improving user convenience.`
    ],
    technologies: ["Java", "Red-Black Tree", "Data Structures"],
  },
];

export const CONTACT = {
  email: "jain.sohalliya@outlook.com",
  linkedin: "https://www.linkedin.com/in/sohalliya-jain/",
  phone: "480-791-7556",
};
